### ISSUE TITLE
Contact icons blending with the background in dark mode

### ISSUE THREAD

**Issue by aaudreychan** [demiahmed/gradshow21#10]
In the dark mode, the icons for email, portfolio, instagram etc goes missing as it blends with the background. Anyway to invert the icon colours?

**Comment by demiahmed** [comment]
Once you enable the script for dark mode, the icons should automatically invert as in the screenshot below

![image](https://user-images.githubusercontent.com/40930082/139541442-6fefca1a-f8dc-4be6-a6a2-a75c15122834.png)


Please refresh your browser using Ctrl+Shift+R to clear cache and make sure the darkmode file is enabled.
