### ISSUE TITLE
Hero image background colour and alignment

### ISSUE THREAD

**Issue by ghost** [demiahmed/gradshow21#11]
![image](https://user-images.githubusercontent.com/93384271/139432198-a0506035-6fbf-4b56-8d42-c137546742c5.png)

The hero image doesn't align horizontally, with the top of the image being cropped off, and the bottom having a lot of empty space. The image is a png, and the edges are supposed to be transparent, but the background colour doesn't match the rest of the body and is instead the gray.

**Comment by demiahmed** [comment]
May I know whats the resolution and aspect ratio of the image?

**Comment by benchomuncho** [comment]
It's currently 1920x969 or about 2:1. The recommended aspect ratio of 16:9 is too tall for the entire image to be displayed. I have also tried at 1500x757 and the problem still persists.

**Comment by demiahmed** [comment]
Can you try placing your image in the 16:9 canvas and then add black borders to the top or the sides? 

Ideally I would resize/redesign my cover image to suit the 16:9 ratio since this site is gonna be viewed worldwide across a variety of devices. Following a standard really helps for you

**Comment by benchomuncho** [comment]
Sure, but this solves neither the horizontal alignment issue nor the background colour issue.

![image](https://user-images.githubusercontent.com/93384271/139619370-b9959c1a-b505-4463-b441-e8d3e8c8c174.png)

**Comment by demiahmed** [comment]
Please make a submission for now and I will have a look at your files directly, try to investigate the issue

**Comment by benchomuncho** [comment]
I submitted yesterday before the deadline. I have updated the hero image with the 16:9 aspect ratio.

**Comment by benchomuncho** [comment]
Just an update, I found that the background colour is due to the dark mode plugin on my browser which doesn't disable itself unless I go into the page element.
Thanks for updating the banner alignment, but now the bottom of the image is cut off.
![image](https://user-images.githubusercontent.com/93384271/144438236-c564774a-0450-4fd9-a61a-d10be2224e01.png)

**Comment by demiahmed** [comment]
Best bet is to use strict 1920x1080 instead of 16:9

**Comment by benchomuncho** [comment]
The image is already 1920 x 1080. The aspect ratio is not the problem.

**Comment by benchomuncho** [comment]
Hi, the single image and hero images were all ok yesterday, but today the bottom is cropped off again. All my images are 1920x1080.
