### ISSUE TITLE
Text not aligned

### ISSUE THREAD

**Issue by xinyan-lim** [demiahmed/gradshow21#14]
![chrome_M0XrjaxirZ](https://user-images.githubusercontent.com/93577219/143797381-46474a2a-1506-42cb-99a6-f98cfaf78c00.png)

Can we have an option to have a text box only that aligns with the 16:9 image aspect ratio?

**Comment by demiahmed** [comment]
can you share a screenshot of your HTML that's causing this issue?

**Comment by demiahmed** [comment]
![image](https://user-images.githubusercontent.com/40930082/143806337-976f3970-3632-4c0a-bb76-7f80dd3d52d1.png)

![image](https://user-images.githubusercontent.com/40930082/143806343-818f8849-3ff4-483b-9b44-e2414eba4ddf.png)

I am able to recreate this and working on fixing it. This feature will be available for use in about 16-20 hours when the cache is refreshed.

You may wanna use `<img-caption content="My caption for the image"></img-caption>`

**Comment by xinyan-lim** [comment]
hi ahmed, right now on the https://www.demiahmed.live/gradshow21/projects/2021/lim-xinyan/
it looks like this
![chrome_M0XrjaxirZ](https://user-images.githubusercontent.com/93577219/143808280-c1142f47-c698-4d38-9927-aaf62058ee4f.png)

**Comment by demiahmed** [comment]
@xinyan-lim you need to use the `img-caption` tag to insert. 

Please refer to my above comment. 

I have done an example in the chrome inspect tools in the screenshot below for your reference.

![image](https://user-images.githubusercontent.com/40930082/143808540-c0703fa2-11eb-4429-87db-4615a1486224.png)


Kindly close this issue if it helped. 
Thanks

**Comment by xinyan-lim** [comment]
okay great. thank you, will test it out.

**Comment by xinyan-lim** [comment]
is it possible for the text box feature to be justified with the last line aligned left and also the code <img-caption content="My caption for the image"></img-caption> you gave me does not align with the left and right borders of the special image feature.

**Comment by demiahmed** [comment]
If you want to insert a caption for an image, then use `img-caption` which will be center aligned by default.

Alternatively, you can use a `text-only` component for inserting a title and text which will start from the left.
